version: '3'

services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    environment:
      MONGO_URI: "mongodb://localhost:27017/intern"

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=intern
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
